"""访客存储。双后端：
- 本地默认 SQLite（标准库 sqlite3，零依赖、易演示）。
- 设置 DATABASE_URL=postgres://... 时切到 PostgreSQL（云上 App Runner + Neon）。

两种后端共用同一套调用接口，方言差异（占位符、自增主键、UPSERT、唯一冲突异常）
全部封装在下方 _Conn / _Cursor 适配层，业务函数无需感知用的是哪种库。
"""
import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path

from config import (
    DATABASE_PATH,
    DATABASE_TIMEOUT_SECONDS,
    DATABASE_URL,
    SQLITE_BUSY_TIMEOUT_MS,
)


COMPANY_SEED_PATH = Path(__file__).resolve().parent / "data" / "companies.json"

IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

if IS_POSTGRES:
    import psycopg
    from psycopg.rows import dict_row

    _INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)
    # 自增主键 / UPSERT 的方言写法
    _PK = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    _INSERT_IGNORE_ALIAS = (
        "INSERT INTO company_aliases (company_id, alias, created_at) "
        "VALUES (?, ?, ?) ON CONFLICT (alias) DO NOTHING"
    )
else:
    _INTEGRITY_ERRORS = (sqlite3.IntegrityError,)
    _PK = "INTEGER PRIMARY KEY AUTOINCREMENT"
    _INSERT_IGNORE_ALIAS = (
        "INSERT OR IGNORE INTO company_aliases (company_id, alias, created_at) "
        "VALUES (?, ?, ?)"
    )


class DuplicateCallError(Exception):
    """并发场景下同一 source_call_id 已经被登记。"""


def _to_pg(sql):
    """把 SQLite 占位符 ? 转成 psycopg 的 %s。SQL 文本里没有字面量 ? / %，安全替换。"""
    return sql.replace("?", "%s")


class _Cursor:
    def __init__(self, cur):
        self._cur = cur

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    @property
    def lastrowid(self):
        return self._cur.lastrowid


class _Conn:
    """统一连接包装：execute 返回行为一致的游标；插入取自增 id 走 execute_returning_id。"""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=()):
        params = tuple(params)
        if IS_POSTGRES:
            cur = self._raw.cursor()
            cur.execute(_to_pg(sql), params)
            return _Cursor(cur)
        return _Cursor(self._raw.execute(sql, params))

    def execute_returning_id(self, sql, params=()):
        """INSERT 后取新行 id。Postgres 用 RETURNING id，SQLite 用 lastrowid。"""
        if IS_POSTGRES:
            row = self.execute(sql + " RETURNING id", params).fetchone()
            return row["id"] if row else None
        return self.execute(sql, params).lastrowid

    def commit(self):
        self._raw.commit()


@contextmanager
def get_conn():
    if IS_POSTGRES:
        raw = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            connect_timeout=max(1, int(DATABASE_TIMEOUT_SECONDS)),
        )
    else:
        raw = sqlite3.connect(DATABASE_PATH, timeout=DATABASE_TIMEOUT_SECONDS)
        raw.row_factory = sqlite3.Row
        raw.execute(f"PRAGMA busy_timeout = {SQLITE_BUSY_TIMEOUT_MS}")
    try:
        yield _Conn(raw)
        raw.commit()
    finally:
        raw.close()


def init_db():
    with get_conn() as conn:
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS visitors (
                id {_PK},
                plate_number TEXT NOT NULL,
                company TEXT NOT NULL,
                phone TEXT NOT NULL,
                reason TEXT NOT NULL,
                entry_time TEXT NOT NULL,
                source_call_id TEXT,
                raw_payload TEXT,
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS companies (
                id {_PK},
                name TEXT NOT NULL UNIQUE,
                active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS company_aliases (
                id {_PK},
                company_id INTEGER NOT NULL,
                alias TEXT NOT NULL UNIQUE,
                created_at TEXT NOT NULL,
                FOREIGN KEY(company_id) REFERENCES companies(id)
            )
            """
        )
        # 部分唯一索引：SQLite 与 Postgres 语法一致，保证 source_call_id 幂等
        conn.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_visitors_source_call_id_unique
            ON visitors(source_call_id)
            WHERE source_call_id IS NOT NULL
            """
        )
        if not IS_POSTGRES:
            conn.execute("PRAGMA journal_mode = WAL")
        _seed_companies_if_empty(conn)


def _seed_companies_if_empty(conn):
    """Demo 默认公司目录。只在空表初始化，后续人工维护不会被覆盖。"""
    row = conn.execute("SELECT COUNT(*) AS n FROM companies").fetchone()
    if row["n"] > 0:
        return
    if not COMPANY_SEED_PATH.exists():
        return
    data = json.loads(COMPANY_SEED_PATH.read_text(encoding="utf-8"))
    now = datetime.now().isoformat(timespec="seconds")
    for item in data.get("companies", []):
        name = (item.get("name") or "").strip()
        if not name:
            continue
        company_id = conn.execute_returning_id(
            "INSERT INTO companies (name, active, created_at) VALUES (?, 1, ?)",
            (name, now),
        )
        for alias in item.get("aliases", []):
            alias = (alias or "").strip()
            if not alias:
                continue
            conn.execute(_INSERT_IGNORE_ALIAS, (company_id, alias, now))


def load_company_registry():
    """返回 {标准公司名: {aliases: [...]}}，作为公司实体解析的权威数据源。"""
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT id, name
            FROM companies
            WHERE active = 1
            ORDER BY id ASC
            """
        ).fetchall()
        registry = {}
        for row in rows:
            aliases = conn.execute(
                """
                SELECT alias
                FROM company_aliases
                WHERE company_id = ?
                ORDER BY id ASC
                """,
                (row["id"],),
            ).fetchall()
            registry[row["name"]] = {"aliases": [r["alias"] for r in aliases]}
        return registry


def find_by_call_id(source_call_id):
    """幂等用：同一通电话只登记一次。"""
    if not source_call_id:
        return None
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM visitors WHERE source_call_id = ? ORDER BY id DESC LIMIT 1",
            (source_call_id,),
        ).fetchone()
        return dict(row) if row else None


def find_latest_by_phone(phone):
    """回访识别用（Phase 6）：按手机号查最近一次记录。"""
    if not phone:
        return None
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM visitors WHERE phone = ? ORDER BY id DESC LIMIT 1",
            (phone,),
        ).fetchone()
        return dict(row) if row else None


def find_latest_by_plate(plate_number):
    """对话内回访识别（决策 007）：按车牌精确查最近一次记录。
    与门卫查询里的 LIKE 模糊不同，这里要精确匹配，避免误把别的车当成回访。"""
    if not plate_number:
        return None
    with get_conn() as conn:
        row = conn.execute(
            "SELECT * FROM visitors WHERE plate_number = ? ORDER BY id DESC LIMIT 1",
            (plate_number,),
        ).fetchone()
        return dict(row) if row else None


def count_by_plate(plate_number):
    """精确车牌的历史到访次数（决策 007 lookup 用）。"""
    if not plate_number:
        return 0
    with get_conn() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS n FROM visitors WHERE plate_number = ?",
            (plate_number,),
        ).fetchone()
        return row["n"]


def insert_visitor(data):
    with get_conn() as conn:
        try:
            return conn.execute_returning_id(
                """
                INSERT INTO visitors
                (plate_number, company, phone, reason, entry_time, source_call_id, raw_payload, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    data["plate_number"],
                    data["company"],
                    data["phone"],
                    data["reason"],
                    data["entry_time"],
                    data.get("source_call_id"),
                    json.dumps(data, ensure_ascii=False),
                    datetime.now().isoformat(timespec="seconds"),
                ),
            )
        except _INTEGRITY_ERRORS as e:
            raise DuplicateCallError(data.get("source_call_id")) from e


def list_visitors(limit=20):
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT id, plate_number, company, phone, reason, entry_time, created_at
            FROM visitors ORDER BY id DESC LIMIT ?
            """,
            (limit,),
        ).fetchall()
        return [dict(r) for r in rows]


# ---- 门卫查询 Agent 用：参数化条件查询。字段白名单写死、值全部走占位符，零注入 ----

def _build_filters(
    company=None,
    date=None,
    reason=None,
    plate_number=None,
    phone=None,
    date_from=None,
    date_to=None,
):
    clauses, params = [], []
    if company:
        clauses.append("company LIKE ?")
        params.append(f"%{company}%")
    if reason:
        clauses.append("reason LIKE ?")
        params.append(f"%{reason}%")
    if plate_number:
        clauses.append("plate_number LIKE ?")
        params.append(f"%{plate_number}%")
    if phone:
        clauses.append("phone = ?")
        params.append(phone)
    if date:
        clauses.append("entry_time LIKE ?")
        params.append(f"{date}%")
    if date_from:
        clauses.append("entry_time >= ?")
        params.append(f"{date_from} 00:00:00")
    if date_to:
        clauses.append("entry_time < ?")
        params.append(f"{date_to} 00:00:00")
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    return where, params


def count_visitors(
    company=None,
    date=None,
    reason=None,
    plate_number=None,
    phone=None,
    date_from=None,
    date_to=None,
):
    where, params = _build_filters(company, date, reason, plate_number, phone, date_from, date_to)
    with get_conn() as conn:
        row = conn.execute(f"SELECT COUNT(*) AS n FROM visitors{where}", params).fetchone()
        return row["n"]


def query_visitors(
    company=None,
    date=None,
    reason=None,
    plate_number=None,
    phone=None,
    date_from=None,
    date_to=None,
    limit=10,
):
    limit = max(1, min(int(limit or 10), 50))
    where, params = _build_filters(company, date, reason, plate_number, phone, date_from, date_to)
    with get_conn() as conn:
        rows = conn.execute(
            f"""
            SELECT id, plate_number, company, phone, reason, entry_time
            FROM visitors{where} ORDER BY id DESC LIMIT ?
            """,
            list(params) + [limit],
        ).fetchall()
        return [dict(r) for r in rows]


def group_visitors_by(field, company=None, date=None, reason=None, plate_number=None, phone=None, date_from=None, date_to=None):
    """按公司或事由聚合统计。field 只允许白名单字段，避免动态 SQL 注入。"""
    if field not in ("company", "reason"):
        raise ValueError("group field must be company or reason")
    where, params = _build_filters(company, date, reason, plate_number, phone, date_from, date_to)
    with get_conn() as conn:
        rows = conn.execute(
            f"""
            SELECT {field} AS name, COUNT(*) AS count
            FROM visitors{where}
            GROUP BY {field}
            ORDER BY count DESC, name ASC
            LIMIT 10
            """,
            params,
        ).fetchall()
        return [dict(r) for r in rows]
